"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
pager = "delta"

[user]
name = "Alex Villablanca"
email = "alex@villablanca.tech"

[git]
subprocess = true
sign-on-push = true

[signing]
behavoir = "drop"
backend = "gpg"
